### ISSUE TITLE
touch scroll support

### ISSUE THREAD

**Issue by knightpop** [orteth01/react-scroll-lock-component#12]
Your library is so convenient that I want to use your library in my service. 

but scroll lock works well but not in touch scroll.

do you have any plan to support touch scroll?

**Comment by orteth01** [comment]
@knightpop let me see what I can do this weekend!

**Comment by orteth01** [comment]
@knightpop I didn't have time this weekend but once I get some free time I'll work on adding touch support for you 👍

**Comment by orteth01** [comment]
@knightpop touch events are now supported in 0.3.0
